POST https://node-do-zero-eg30.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video 01",
    "duration": 180
}

### todos

GET https://node-do-zero-eg30.onrender.com/videos


### com busca

GET https://node-do-zero-eg30.onrender.com/videos?search=node


###

PUT https://node-do-zero-eg30.onrender.com/videos/ec55fbf8-d953-4bf0-8893-25a2c8b9532f
Content-Type: application/json

{    
    "title": "Video 2",
    "description": "Esse é o video 01",
    "duration": 180
}

###

DELETE https://node-do-zero-eg30.onrender.com/videos/ec55fbf8-d953-4bf0-8893-25a2c8b9532f